name: Deploy if not a version bump PR
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: gh workflow run deploy.yml
        env:
          GH_TOKEN: ${{ github.token }}
