name: Deploy if not a version bump PR
on:
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: gh workflow run deploy.yml
        env:
          GH_TOKEN: ${{ github.token }}
